# Generated by Django 4.0.6 on 2022-07-16 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_on', models.DateField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=255)),
                ('book_name', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_on', models.DateField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=255)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_on', models.DateField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('active', models.BooleanField()),
                ('role', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LendingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=255)),
                ('modified_on', models.DateField(default=datetime.datetime.now)),
                ('modified_by', models.CharField(max_length=255)),
                ('borrower_username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('current_book_status', models.CharField(choices=[{'A': 'Available', 'B': 'Borrowed'}], max_length=2)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(default=datetime.datetime.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_management.books')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
